services:
  web:
    image: ghcr.io/jasoisjaso/invoice:latest
    restart: unless-stopped
    ports:
      - "5456:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./knowledge:/app/knowledge
      - ./logs:/app/logs

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiNWRmZmUxYzY0NThjOGM5YmJhZjc1ZGU1MTA5OWUyYTYiLCJ0IjoiYTkwYjRiODYtYTkwMy00NTdjLWJjMzUtZGFiMzQzZTU0ZWQyIiwicyI6IlpERTJPR05oTVRNdFpUYzJaQzAwWVRabExXSXdNRFF0T1dZek1EQTJOMkV4TXpkaCJ9
    depends_on:
      - web